import type { UpgradeCandidate } from "./types.ts";

export interface StoryBodyInput {
  candidate: UpgradeCandidate;
  changelogHtml: string | null;
  changelogUrl: string;
}

export function buildStoryTitle(c: UpgradeCandidate): string {
  const plural = c.majorsBehind > 1 ? "s" : "";
  return `Upgrade ${c.package} in ${c.repo} (${c.pinned} -> ${c.latest}, ${c.majorsBehind} major${plural} behind)`;
}

export function buildStoryBody({
  candidate,
  changelogHtml,
  changelogUrl,
}: StoryBodyInput): string {
  const {
    repo,
    package: pkg,
    pinned,
    latest,
    majorsBehind,
    repoUrl,
  } = candidate;
  const plural = majorsBehind > 1 ? "s" : "";

  const migrationSection = changelogHtml
    ? [
        "<h3>Migration guide</h3>",
        `<p>Changes in <b>${escapeHtml(pkg)}</b> between <code>${escapeHtml(pinned)}</code> and <code>${escapeHtml(latest)}</code>:</p>`,
        changelogHtml,
        `<p>Full CHANGELOG: <a href="${changelogUrl}">${changelogUrl}</a></p>`,
      ].join("\n")
    : [
        "<h3>Migration guide</h3>",
        `<p>See the <a href="${changelogUrl}">CHANGELOG for ${escapeHtml(pkg)}</a> for breaking changes between <code>${escapeHtml(pinned)}</code> and <code>${escapeHtml(latest)}</code>.</p>`,
      ].join("\n");

  return [
    "<h3>Context</h3>",
    `<p>The repo <a href="${repoUrl}"><b>${escapeHtml(repo)}</b></a> is using <code>${escapeHtml(pkg)}@${escapeHtml(pinned)}</code> but the latest published version is <code>${escapeHtml(latest)}</code> — that's <b>${majorsBehind} major version${plural} behind</b>.</p>`,
    "",
    "<h3>Risks of not upgrading</h3>",
    "<ul>",
    "  <li>Missing critical accessibility (WCAG 2.2 AA) fixes shipped in newer majors</li>",
    "  <li>Bug fixes and security patches landing only on the latest major</li>",
    "  <li>Drift from the Auro design system — visual / behavioral inconsistency with other ecommerce surfaces</li>",
    "  <li>Breaking changes accumulate; the longer you wait, the riskier the eventual upgrade</li>",
    "</ul>",
    "",
    migrationSection,
    "",
    "<h3>Benefits of upgrading</h3>",
    "<ul>",
    "  <li>Latest a11y improvements + WCAG 2.2 AA token contrast fixes</li>",
    "  <li>Performance and bundle-size improvements</li>",
    "  <li>Continued support — older majors will not receive new fixes</li>",
    "  <li>Stays in sync with the rest of the Auro fleet (lower long-term maintenance cost)</li>",
    "</ul>",
    "",
    "<p><i>This ticket was auto-generated by the Auro Version Support bot.</i></p>",
  ].join("\n");
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
