import type { BreakingChange, ChangelogSlice } from "./changelog.ts";
import type { UpgradeCandidate } from "./types.ts";

export interface StoryBodyInput {
  candidate: UpgradeCandidate;
  changelogSlice: ChangelogSlice | null;
  changelogUrl: string;
  breakingChanges: BreakingChange[];
  /** When this ticket replaces an earlier bot ticket via close-and-recreate. */
  supersedes?: number;
}

/**
 * Generic verification bullets that apply to every upgrade. Per-upgrade
 * specifics (e.g. "verify breaking change X is handled") are appended
 * downstream by `buildAcceptanceCriteria`.
 */
function genericAcceptanceBullets(c: UpgradeCandidate): string[] {
  const pkg = escapeHtml(c.package);
  const latest = escapeHtml(c.latest);
  const target = c.targetPackage ? escapeHtml(c.targetPackage) : null;
  const firstBullet = target
    ? `Replace <code>${pkg}</code> with <code>${target}@${latest}</code> in the consumer's <code>package.json</code> (and lockfile). Update all import paths from <code>${pkg}</code> to <code>${target}</code>.`
    : `Update <code>${pkg}</code> to <code>${latest}</code> in the consumer's <code>package.json</code> (and lockfile).`;
  const smokeRef = target ?? pkg;
  return [
    firstBullet,
    "<code>npm ci</code> succeeds with no peer-dep warnings or lockfile drift caused by the upgrade.",
    "Build / TypeScript compile passes with no new errors introduced by the upgrade.",
    "Lint passes (no new violations).",
    "Existing test suite passes.",
    `Manual smoke check: every UI surface using <code>${smokeRef}</code> renders without new console errors and matches the prior visual baseline.`,
  ];
}

/**
 * Acceptance criteria starts with the generic verification bullets and
 * appends one verifiable bullet per breaking change so the reviewer can
 * tick them off individually.
 */
export function buildAcceptanceCriteria(
  c: UpgradeCandidate,
  breakingChanges: BreakingChange[] = [],
): string {
  const bullets = genericAcceptanceBullets(c).map((b) => `  <li>${b}</li>`);
  for (const bc of breakingChanges) {
    bullets.push(
      `  <li>Verify the breaking change introduced in <code>${escapeHtml(bc.version)}</code> is handled: ${renderInline(bc.text)}</li>`,
    );
  }
  return ["<ul>", ...bullets, "</ul>"].join("\n");
}

export function buildStoryTitle(c: UpgradeCandidate): string {
  const plural = c.majorsBehind > 1 ? "s" : "";
  return `Upgrade ${c.package} in ${c.repo} (${c.pinned} -> ${c.latest}, ${c.majorsBehind} major${plural} behind)`;
}

export function buildStoryBody({
  candidate,
  changelogSlice,
  changelogUrl,
  breakingChanges,
  supersedes,
}: StoryBodyInput): string {
  const {
    repo,
    package: pkg,
    pinned,
    latest,
    majorsBehind,
    repoUrl,
  } = candidate;
  const plural = majorsBehind > 1 ? "s" : "";

  const targetPackage = candidate.targetPackage;
  const contextSection = [
    "<h3>Context</h3>",
    `<p>The repo <a href="${repoUrl}"><b>${escapeHtml(repo)}</b></a> is using <code>${escapeHtml(pkg)}@${escapeHtml(pinned)}</code> but the latest published version is <code>${escapeHtml(latest)}</code> — that's <b>${majorsBehind} major version${plural} behind</b>. Staying current keeps a11y, security patches, and design-system parity in step with the rest of the Auro fleet.</p>`,
    targetPackage
      ? `<p><b>⚠ Namespace rename:</b> active development of this library moved to <code>${escapeHtml(targetPackage)}</code>. Upgrading requires renaming the dependency in <code>package.json</code> from <code>${escapeHtml(pkg)}</code> to <code>${escapeHtml(targetPackage)}</code> AND updating any matching import paths in source files. The version number bridges both scopes — <code>${escapeHtml(latest)}</code> is the latest on the new scope.</p>`
      : "",
    supersedes !== undefined
      ? `<p><i>This ticket supersedes work item #${supersedes}, which was closed because a newer version of <code>${escapeHtml(pkg)}</code> has shipped since that ticket was created.</i></p>`
      : "",
  ]
    .filter(Boolean)
    .join("\n");

  const breakingSection = buildBreakingChangesSection(
    pkg,
    pinned,
    latest,
    changelogSlice,
    breakingChanges,
  );

  const migrationSection = changelogSlice
    ? [
        "<h3>Migration guide</h3>",
        `<p>Changes in <b>${escapeHtml(pkg)}</b> between <code>${escapeHtml(pinned)}</code> and <code>${escapeHtml(latest)}</code>:</p>`,
        changelogSlice.html,
        `<p>Full CHANGELOG: <a href="${changelogUrl}">${changelogUrl}</a></p>`,
      ].join("\n")
    : [
        "<h3>Migration guide</h3>",
        `<p>See the <a href="${changelogUrl}">CHANGELOG for ${escapeHtml(pkg)}</a> for changes between <code>${escapeHtml(pinned)}</code> and <code>${escapeHtml(latest)}</code>.</p>`,
      ].join("\n");

  return [
    contextSection,
    "",
    breakingSection,
    "",
    migrationSection,
    "",
    "<p><i>This ticket was auto-generated by the Auro Version Support bot.</i></p>",
  ]
    .filter((s) => s !== "")
    .join("\n");
}

/**
 * Renders a "Breaking changes in this upgrade" section derived from the
 * BREAKING CHANGES subheadings in the CHANGELOG slice. Returns an empty
 * string when the changelog wasn't fetchable (so the section is omitted
 * entirely); returns an explicit "none detected" paragraph when the
 * changelog exists but contains no breaking-change entries.
 */
function buildBreakingChangesSection(
  pkg: string,
  pinned: string,
  latest: string,
  changelogSlice: ChangelogSlice | null,
  breakingChanges: BreakingChange[],
): string {
  if (!changelogSlice) {
    return "";
  }
  if (breakingChanges.length === 0) {
    return [
      "<h3>Breaking changes in this upgrade</h3>",
      `<p>No breaking changes detected in <code>${escapeHtml(pkg)}</code> between <code>${escapeHtml(pinned)}</code> and <code>${escapeHtml(latest)}</code>.</p>`,
    ].join("\n");
  }
  const bullets = breakingChanges
    .map(
      (bc) =>
        `  <li><b>${escapeHtml(bc.version)}:</b> ${renderInline(bc.text)}</li>`,
    )
    .join("\n");
  return [
    "<h3>Breaking changes in this upgrade</h3>",
    "<ul>",
    bullets,
    "</ul>",
  ].join("\n");
}

function renderInline(text: string): string {
  // Inline markdown that survives raw in a CHANGELOG bullet: `code` and
  // [label](url) links. Escape first so URL chars are safe before we
  // re-inject HTML tags.
  let html = escapeHtml(text);
  html = html.replace(/`([^`]+)`/g, "<code>$1</code>");
  html = html.replace(
    /\[([^\]]+)\]\(([^)]+)\)/g,
    (_match, label, url) => `<a href="${url}">${label}</a>`,
  );
  return html;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
