/**
 * Frozen layout for the files `auro init` writes: the canonical `AGENTS.md`
 * grounding file and the thin `CLAUDE.md` that imports it.
 *
 * FROZEN per docs/pt-m1-completion-plan.md → build-order step 1 ("freeze the file
 * format") and "Frozen decisions → `AGENTS.md` vs data files". This module owns
 * the input-INDEPENDENT scaffolding only: the header/intro, the frozen top-level
 * section order, the regeneration note, and the `CLAUDE.md` body. The generator
 * (build-order step 4) fills the per-component API bodies and the resolved
 * tag/import/registration lines around this scaffolding; it must not re-derive
 * these constants.
 *
 * @see {@link AURO_CODING_RULES} in ./rules.ts for the "Auro Coding Rules" body.
 * @see test/fixtures/init/ for the golden assembled documents this pins.
 */

/**
 * Canonical name of the grounding file. `CLAUDE.md` imports this by name, so the
 * two must agree.
 */
export const AGENTS_FILENAME = "AGENTS.md";

/** The thin per-assistant import file name. */
export const CLAUDE_FILENAME = "CLAUDE.md";

/**
 * Frozen top-level section order of `AGENTS.md`. The generator emits these H2
 * sections in exactly this order; the per-component subsections (H3) live under
 * "Installed Components". Changing this order is a format change (see module
 * doc) — bump behavior deliberately, don't reorder ad hoc.
 */
export const SECTION_HEADINGS = [
  "What is Auro?",
  "Auro Coding Rules",
  "Installed Components",
  "Regeneration",
] as const;

/**
 * The document header + intro + "What is Auro?" section — everything above the
 * coding rules. Input-independent, so it lives here as a frozen constant.
 */
export const GROUNDING_HEADER = `# Auro Design System — AI Assistant Grounding

<!-- Generated by \`auro init\`. Do not edit by hand — re-run \`auro init\` to
regenerate. Custom element tags are governed by \`auro.config.json\`. -->

Alaska Airlines open-source design system | https://auro.alaskaair.com

This file grounds AI assistants in the Auro components **installed in this
project**. It lists only installed packages, their exact registered tags, and the
full API for the installed version of each component. Treat it as authoritative
for this project.

## What is Auro?

Auro is Alaska Airlines' design system, built on Web Components (Custom Elements
v1) using the Lit library.
- npm scope: \`@aurodesignsystem/\` (current), \`@alaskaairux/\` (legacy)
- Framework-agnostic: works with React, Angular, Vue, Svelte, or plain HTML
- Each component is a separate npm package and registers a custom element tag
`;

/**
 * Column header for the "Installed Components" summary table. The generator
 * emits one row per resolved component beneath it.
 */
export const INSTALLED_TABLE_HEADER = `| Tag | Package | Version | Import |
|---|---|---|---|`;

/**
 * The closing "Regeneration" section. Input-independent, so it's frozen here.
 */
export const REGENERATION_NOTE = `## Regeneration

This file is generated by \`auro init\`. Re-run it after adding or removing an Auro
dependency to update the component list and APIs. Custom element tags are governed
by \`auro.config.json\` (committed by default) — change prefixes there, not in this
file, then re-run \`auro init\`.
`;

/**
 * The entire body of the generated \`CLAUDE.md\`: a thin import of \`AGENTS.md\` so a
 * single canonical grounding file serves every assistant target (task #5). This
 * is the ONLY justified indirection (see "Frozen decisions → \`AGENTS.md\` vs data
 * files").
 */
export const CLAUDE_MD = `@${AGENTS_FILENAME}
`;
